/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.service.access.policy.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.service.access.policy.model.ServiceAccessPolicy;
import com.liferay.service.access.policy.service.ServiceAccessPolicyLocalServiceUtil;

/**
 * The extended model base implementation for the ServiceAccessPolicy service. Represents a row in the &quot;ServiceAccessPolicy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ServiceAccessPolicyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServiceAccessPolicyImpl
 * @see com.liferay.service.access.policy.model.ServiceAccessPolicy
 * @generated
 */
@ProviderType
public abstract class ServiceAccessPolicyBaseImpl
	extends ServiceAccessPolicyModelImpl implements ServiceAccessPolicy {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a service access policy model instance should use the {@link ServiceAccessPolicy} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ServiceAccessPolicyLocalServiceUtil.addServiceAccessPolicy(this);
		}
		else {
			ServiceAccessPolicyLocalServiceUtil.updateServiceAccessPolicy(this);
		}
	}
}